Hello: Hello

User: User
Users: Users
Name: Name
Password: Password
Employment: Employment
FamilyStatus: Family status

Emails: Emails
Email: Email
Ident: Ident
Verkey: Verification key

EmploymentEmployed  : Employed 
EmploymentUnemployed: Unemployed
EmploymentRetired   : Retired

FamilyStatusSingle  : Single
FamilyStatusMarried : Married
FamilyStatusDevorsed: Devorsed    
FamilyStatusWidowed : Widowed