Hello: Hello

Dictionary: Справочник
Save: Сохранить
Saved: Сохранено...
Error err@Text: Ошибка: #{err}

User: Пользователь
Users: Пользователи
Name: Имя
Password: Пароль
Emails: Email'ы
Email: Email
Ident: Идентификатор
Verkey: Проверочный ключ

ListDic dic@Text: Список #{dic}
Id: Ключ

#pager
RecCount cnt@Int: Кол-во записей: #{show cnt}
PageCount cnt@Int: Кол-во страниц: #{show cnt}
PageSize: Размер страницы:
Page: Страница
GoToFirstBtn: На первую запись
PrevPageBtn: Предыдущая страница
NextPageBtn: Следующая страница
GoToLastBtn: На последнюю запись
Of: из

#errors
InvalidKey dic@Text val@Text err@Text: Ошибочный ключ "#{val}" для справочника "#{dic}". Ошибка: "#{err}"
NotFound dic@Text val@Text: Не найден ключ "#{val}" для справочника "#{dic}"

