Hello: Hello

User: Пользователь
Users: Пользователи
Name: Имя
Password: Пароль
Employment: Занятость
FamilyStatus: Семейное положение

Emails: Адреса эл.почты
Email: Адрес эл.почты
Ident: Идентификатор
Verkey: Проверочный ключ

EmploymentEmployed  : Нанят
EmploymentUnemployed: Безработный
EmploymentRetired   : Уволен

FamilyStatusSingle  : Холост
FamilyStatusMarried : Женат
FamilyStatusDevorsed: Разведен
FamilyStatusWidowed : Вдов