Hello: Hello

User: Пользователь
Users: Пользователи
Name: Имя
Password: Пароль
Employment: Занятость
FamilyStatus: Семейное положение

Emails: Адреса эл.почты
Email: Адрес эл.почты
Ident: Идентификатор
Verkey: Проверочный ключ

EmploymentEmployed  : Работает
EmploymentUnemployed: Безработный
EmploymentRetired   : Уволен

FamilyStatusSingle  : Холост
FamilyStatusMarried : Женат
FamilyStatusDevorsed: Разведен
FamilyStatusWidowed : Вдов

InvalidEmailF: Неверный почтовый адрес. Адрес должен быть в форме <что угодно>@<что угодно>.<что угодно> и не содержать пробелов