Dictionary dic@Text: Dictionary #{dic}
SelDictionary dic@Text fld@Text: Select for field "#{fld}" from Dictionary "#{dic}"
Save: Save
Saved: Saved...
Error err@Text: Error: #{err}

#ListDic dic@Text: List of #{dic}
Id: Key

#pager
RecCount: Count of record:
PageCount: Count of pages:
PageSize: Size of page:
Page: Page
GoToFirstBtn: Go to the first record
PrevPageBtn: Previous page
NextPageBtn: Next page
GoToLastBtn: Go to the last record
Of: of

Select: Select

#errors
InvalidKey dic@Text val@Text err@Text: The key "#{val}" for dictionary "#{dic}" is invalid. An error: "#{err}"
NotFound dic@Text val@Text: Not found key "#{val}" for dictionary "#{dic}"


