Dictionary dic@Text: Справочник #{dic}
SelDictionary dic@Text fld@Text: Выбор поля "#{fld}" из справочника "#{dic}" 
Save: Сохранить
Saved: Сохранено...
Error err@Text: Ошибка: #{err}

#ListDic dic@Text: Список #{dic}
Id: Ключ

#pager
RecCount: Кол-во записей: 
PageCount: Кол-во страниц: 
PageSize: Размер страницы:
Page: Страница
GoToFirstBtn: На первую запись
PrevPageBtn: Предыдущая страница
NextPageBtn: Следующая страница
GoToLastBtn: На последнюю запись
Of: из

Select: Выбрать

#errors
InvalidKey dic@Text val@Text err@Text: Ошибочный ключ "#{val}" для справочника "#{dic}". Ошибка: "#{err}"
NotFound dic@Text val@Text: Не найден ключ "#{val}" для справочника "#{dic}"

